### ISSUE TITLE
Add a tile gardient?

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/frontend#54]
## Idee/Original:
![grafik](https://user-images.githubusercontent.com/5003424/210886536-542b600d-fa13-4f79-b8ef-da026acab81d.png)

----

## First try / Quick & Dirty
![grafik](https://user-images.githubusercontent.com/5003424/210886518-78d47781-e53c-4aaa-a428-cda951144b44.png)

![grafik](https://user-images.githubusercontent.com/5003424/210886792-1c6f8974-c5b8-4e96-a778-5bdbd09fbb6b.png)

![grafik](https://user-images.githubusercontent.com/5003424/210887176-18b640ec-5390-4c09-a116-a7e76503f25c.png)

In _Tile.vue_
```css
.card-body {
  background: linear-gradient(
    45deg,
    rgba(0, 36, 22, 0.281) 10%,
    rgba(9, 44, 121, 0.082) 50%,
    rgba(0, 213, 255, 0.041) 100%
  );
}
```
