### ISSUE TITLE
Change notification color schema (to match the bootstrap color schema)

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/frontend#55]
Quick & dirty while developet the login page:

```css
.notification-list-item--alert .notification-list-item__tag[data-v-0730d53e] {
    background-color: var(--bs-red) !important;
}

.notification-list-item--info .notification-list-item__icon[data-v-0730d53e] {
    background-color: var(--bs-blue) !important;
}

.notification-list-item--success .notification-list-item__tag[data-v-0730d53e] {
    background-color: var(--bs-green) !important;
}
```

Add this to _base.css_
But what when data data attribute changes?
Remove that from the css selector?!
