### ISSUE TITLE
set navbar items `min-width` dynamicly based on screen size/orientation

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/frontend#59]
Related to #5

Since [5259787](https://github.com/OpenHausIO/frontend/commit/525978758ee2bfdd416fb957bf9e9a859817d809) the navbar scrolls horizontal on overflow.
This is good for small screens.

But the `min-width` value must be calculated dynamic based on the screen resolution and orientation.
```css
ul.navbar-nav li a{
  min-width: 160px;
}
```
Looks good on my tablet, but terrible on my phone.

```css
ul.navbar-nav li a{
  min-width: 100px;
}
```
Looks good on the phone, but terrible on the table.

Set that value based on media queries.
