### ISSUE TITLE
Smooth backround gradient

### ISSUE THREAD

**Issue by mStirner** [OpenHausIO/frontend#62]
In Firefox the background gradient has artifacts and no smooth color fade.
In Chromium it looks much better. 

See for details: https://stackoverflow.com/q/75069691/5781499

**Comment by mStirner** [comment]
Backup before fix:


```css
#app.gardien-background {
    background-color: #2e3236;
    background-image: radial-gradient(circle, #4e505298 0, rgba(35, 40, 46, .5) 15%, #101418 95%);
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
}
```
